### ISSUE TITLE
Provide documentation for SSH and SCP

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-documentation#537] opened 2023-09-18 11:57 UTC
It's possible to SSH into an Altis Cloud server and to use SCP but this does not appear to be documented anywhere, at least searching for either of those terms on the documentation site returns no relevant results.

This feature is provided by Altis CLI, however that package provides no documentation beyond the list of available commands.

It would be great to see documentation that covers SSH and SCP with usage examples.

**Comment by rmccue** [comment] 2024-01-31 12:42
Duplicate of #536.

**Closed by rmccue** 2024-01-31 12:42 UTC
