### ISSUE TITLE
Old docs redirection

### ISSUE THREAD

**Issue by missjwo** [humanmade/altis-documentation#596] opened 2024-12-04 11:01 UTC
Currently we have old documentation links that are no longer used but are still being served. Because of this, we have a handful of old docs which have no style sheet and also no way to redirect those links to anything useful. 

We need to create a way to set redirections for old documentation links.

**Comment by rmccue** [comment] 2024-12-04 12:19
Duplicate of https://github.com/humanmade/altis-dev-docs-site/issues/132

**Closed by rmccue** 2024-12-04 12:19 UTC
Labels: epic
